### ISSUE TITLE
adding FAQ to github.io

### ISSUE THREAD

**Issue by rsharifnasab** [MSDehghan/SBDL#4]
hi, as you know every year many students use this library and they have minor and major problems every day (and in every line of code) 
it would be good to adding ** a FAQ page ** or at least create a list and add some major mistakes the students do, for example they load textures and fonts before initializing whole SBDL and it cause unsuccessful load. we can have a least to mention this common mistakes.

**Comment by MSDehghan** [comment]
Yes yes. very good idea.
github.io page should be redesigned also.
Can you put this in todo section please??

And also if you know more FAQs please tell them here in this issue.

Thank you so much.

**Comment by rsharifnasab** [comment]
added to readme, please merge it :)) #3 
no i can't mention any specific question, bet if there is an active FAQ page, TA's will contribute to it soon in next semesters!
